#!/bin/sh
branch=$(git symbolic-ref --short HEAD)

# Autoriser uniquement les branches commençant par feature/, bugfix/, ou hotfix/
if ! echo "$branch" | grep -qE "^(feature/|bugfix/|hotfix/)"; then
  echo "❌ Commits are only allowed on feature/, bugfix/, or hotfix/ branches."
  echo "Your current branch is '$branch'."
  echo "Please create a branch with a valid name before committing."
  exit 1
fi

# Si la branche est valide, continuez avec les autres vérifications
npx lint-staged
